import type { Theme } from '@/types/theme'

export const warmTheme: Theme = {
  id: 'warm',
  name: '留白相册',
  description: '相册书翻页，一页照片一页手记',
  layoutMode: 'minimal',
  appearance: 'light',
  cssVars: {
    '--surface': '#F8F8F5',
    '--surface-panel': '#F8F8F5',
    '--surface-card': '#FDFDFB',
    '--surface-elevated': '#EFEFEB',
    '--surface-hover': 'rgba(47, 51, 54, 0.04)',
    '--surface-warm': 'linear-gradient(135deg, #F8F8F5 0%, #E8E7E1 100%)',
    '--text': '#25282A',
    '--text-secondary': '#555B5E',
    '--text-muted': '#8B9091',
    '--text-inverse': '#F8F8F5',
    '--border': '#E4E4DE',
    '--border-focus': 'rgba(47, 51, 54, 0.34)',
    '--accent': '#2F3336',
    '--accent-strong': '#1E2224',
    '--accent-soft': 'rgba(47, 51, 54, 0.07)',
    '--accent-honey': '#A18B6A',
    '--accent-leaf': '#7D8A7B',
    '--accent-ink': '#2F3336',
    '--shadow-panel': 'none',
    '--shadow-card': 'none',
    '--shadow-hover': '0 8px 22px rgba(47, 51, 54, 0.06)',
    '--radius': '2px',
    '--section': '132px',
    '--card-radius': '0px',
    '--card-padding': '44px',
    '--card-gap': '96px',
    '--card-shadow': 'none',
    '--card-image-height': '420px',
    '--card-image-ratio': '4/3',
    '--post-media-ratio-minimal': '4/3',
    '--album-max-width': '66rem',
    '--font-weight-title': '300',
    '--font-weight-body': '300',
    '--font-size-title': '18px',
    '--font-size-body': '14px',
    '--section-spacing': '60px',
    '--page-padding': '40px',
    '--font-family-title': 'inherit'
  }
}
